export const GET_BREWERIES_LIST = 'GET_BREWERIES_LIST';
export const CLEAR_BREWERIES_LIST = 'CLEAR_BREWERIES_LIST';
export const NO_DATA_PROVINCE = 'NO_DATA_PROVINCE';
export const SET_INPUT = 'SET_INPUT';
export const SET_LOADING = 'SET_LOADING';
